import Head from "next/head"
import Navbar from "../components/Navbar"
import Main from "../components/Main"
import About from "../components/About"
import Skills from "../components/Skills"
import Projects from "../components/Projects"
import Contact from "../components/Contact"
import Contactme from "../components/ayat"




export default function Home() {
  return (
    <div >
      <Head>
        <title>Ayat&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main />
      <About/>
      <Skills/>
      <Projects/>
      <Contact />
      <Contactme />

    </div>
  )
}
